baseURL = "https://john.doe.io/"
title = "John Doe"
author = "John"
copyright = "CC BY-SA 4.0"
languageCode = "en-US"
theme = 'hugo-baerenstark'
enableRobotsTXT = true
paginate = 3

#disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  description = "John's Blog"
  favicon = "images/favicon.png"
  mainSections = ["posts"]

[menu]
  [[menu.main]]
    name       = "Writing"
    url        = "/posts"
    weight     = -100
  [[menu.main]]
    name       = "Projects"
    url        = "/projects"
    weight     = -50
  [[menu.main]]
    name       = "Tags"
    url        = "/tags"
    weight     = -50
  [[menu.main]]
    name       = "About"
    url        = "/pages/about/"
    weight     = -10

[markup]
  [markup.highlight]
    # highligt styles are defined in style.html for both light and dark color schemes
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
