baseURL = "https://john.doe.io/"
title = "John Doe"
author = "John"
copyright = "CC BY-SA 4.0"
languageCode = "en-US"
theme = 'hugo-baerenstark'
enableRobotsTXT = true
paginate = 3

[params]
  description = "John's Blog"
  favicon = "images/favicon.png"

[menu]
  [[menu.main]]
    identifier = "index"
    name       = "Writing"
    url        = "/"
    weight     = -100

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/pages/about/"
    weight     = -10

[markup]
  [markup.highlight]
    # highligt styles are defined in style.html for both light and dark color schemes
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
